version: '3'
services:
  zookeeper:
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: "always"
    image: "zookeeper:${ZOOKEEPER_VERSION}"
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZK_SERVERS: "zookeeper:2888:3888"
    volumes:
      - "./zookeeper-data:/data"

  kafka:
    container_name: ${COMPOSE_KAFKA_PROJECT_NAME}
    restart: "always"
    image: "confluentinc/cp-kafka:${KAFKA_VERSION}"
    ports:
      - "${KAFKA_PORT}:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - "./kafka-data:/data"